name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Sonar Scanner
        run: |
          wget -O sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonarscanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"

      - name: Run Terraform linter
        run: |
          wget -O tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.34.1/tflint_linux_amd64.zip
          unzip tflint.zip -d $HOME
          export PATH="$HOME:$PATH"
          tflint --init
          tflint

      - name: Run Docker linter
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-Linux-x86_64
          chmod +x hadolint
          export PATH="$PATH:$(pwd)"
          hadolint Dockerfile

      - name: Run KubeLinter
        run: |
          wget -O kubelinter.tar.gz https://github.com/stackrox/kube-linter/releases/download/v0.2.2/kube-linter-linux.tar.gz
          tar -xzf kubelinter.tar.gz
          chmod +x kube-linter
          export PATH="$PATH:$(pwd)"
          kube-linter lint .

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
